// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Z1oz0gyNNCJDLXZ581x0E0jYK5QZLrU',
    appId: '1:477222075884:web:1057d84d6f7b332a3514c9',
    messagingSenderId: '477222075884',
    projectId: 'threads-a6c88',
    authDomain: 'threads-a6c88.firebaseapp.com',
    storageBucket: 'threads-a6c88.appspot.com',
    measurementId: 'G-M77FNNXETN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL_aonJ8qJNZe9WzcsTnFtwsKO-EcQpYo',
    appId: '1:477222075884:android:4d5baf2b57814dfe3514c9',
    messagingSenderId: '477222075884',
    projectId: 'threads-a6c88',
    storageBucket: 'threads-a6c88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHTdDhRJym3PPJZutHCFWvLXI5FjJJms',
    appId: '1:477222075884:ios:fc1f5816291990ca3514c9',
    messagingSenderId: '477222075884',
    projectId: 'threads-a6c88',
    storageBucket: 'threads-a6c88.appspot.com',
    iosBundleId: 'com.example.threadsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHTdDhRJym3PPJZutHCFWvLXI5FjJJms',
    appId: '1:477222075884:ios:b601fcbfa60bf3b33514c9',
    messagingSenderId: '477222075884',
    projectId: 'threads-a6c88',
    storageBucket: 'threads-a6c88.appspot.com',
    iosBundleId: 'com.example.threadsClone.RunnerTests',
  );
}
